--- 
abstract: generate a package with methods and variables from
author: 
  - Jonathan Rockway C<< <jrockway@cpan.org> >>
build_requires: 
  Test::Exception: 0
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Package-FromData
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
  Readonly: 0
  Scalar::Util: 0
  Test::Deep::NoTest: 0
  perl: 5.10.0
version: 0.01
